#!/bin/bash
  
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the mudskipper daemons
### END INIT INFO

DAEMON=/usr/local/bin/mudskipper
CONF=/etc/mudskipper.conf
USER=jenkins
DEFAULT_DST_DIR="/mnt/dw-utility0/mudskipper"
DEFAULT_BINLOG_PATH="/var/lib/mysql/"
LOG_PATH="/var/log/mudskipper"
PID_DIR="/var/run/mudskipper"

mkdir -p $PID_DIR
chown $USER $PID_DIR
mkdir -p $LOG_PATH
chown $USER $LOG_PATH
REGEX="([0-9]{4}-[0-9]{2}-[0-9]{2})-([0-9]{6})"
case "$1" in
  start)
    while read -a i
      do
      [[ -z "$i" ]] && continue # skip blank lines
      [[ $i =~ ^# ]] && continue # skip comments
      TABLE=${i[0]}
      DST_DIR=${i[1]} && [[ -z "$DST_DIR" ]] && DST_DIR=$DEFAULT_DST_DIR
      BINLOG_PATH=${i[2]} && [[ -z "$BINLOG_PATH" ]] && BINLOG_PATH=$DEFAULT_BINLOG_PATH
      PID=$PID_DIR/$TABLE.pid
      touch $PID
      chown $USER $PID
      LOG_FILE=$LOG_PATH/$TABLE.log
      touch $LOG_FILE
      chown $USER $LOG_FILE

      echo "Trying to figure out where to start..."
      LAST_NUMBER=`find ${DST_DIR}/* -name \*.in_progress 2>/dev/null | sort | head -n 1`
      if [[ -n $LAST_NUMBER ]]
	then
          [[ $(basename $LAST_NUMBER) =~ $REGEX ]]
	  BINLOG_NUMBER=${BASH_REMATCH[2]}
	else
          LAST_NUMBER=`find ${DST_DIR}/* -name \*.txt* 2>/dev/null | sort | tail -n 1`
          if [[ -n $LAST_NUMBER ]]
            then
              [[ $(basename $LAST_NUMBER) =~ $REGEX ]]
              BINLOG_NUMBER=${BASH_REMATCH[2]}
            else
              BINLOG_NUMBER=`head -n 1 $BINLOG_PATH/mysql-bin.index | cut -d "." -f 3`
          fi 
      fi
      # trim leading zeros
      BINLOG_NUMBER=`echo $BINLOG_NUMBER | sed -r 's/^0+([0-9])/\1/'`

      OPTS="-base_name=mysql-bin -binlog_number=$BINLOG_NUMBER \
      -binlog_path=$BINLOG_PATH -dest_dir=$DST_DIR -table=$TABLE"
      echo -n "Starting mudskipper for $TABLE"
      daemon --output=$LOG_FILE -u $USER --pidfile=$PID -- $DAEMON $OPTS
      echo "."
      
    done <$CONF

  ;;
  stop)
    while read -a i
      do
      [[ -z "$i" ]] && continue # skip blank lines
      [[ $i =~ ^# ]] && continue # skip comments
      TABLE=${i[0]}
      PID=$PID_DIR/$TABLE.pid
	echo -n "Stopping mudskipper for $TABLE"
        ls $PID &>/dev/null || echo "no pid file. Wanted $PID."
        ls $PID &>/dev/null && kill `cat $PID`
        echo "."
      done <$CONF
  ;;

  *)
  echo "Usage: "$1" {start|stop}"
  exit 1
esac

exit 0
